apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage-container
    image: nginx
    command: ["sleep","3600"]

    volumeMounts:
    - name: storage
      mountPath: /workspace

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: storage-pvc