apiVersion: v1
kind: Pod

metadata:
  name: volume-pod
  namespace: hr

spec:
  containers:
  - name: nginx-container
    image: nginx

    volumeMounts:
    - name: maihar-volume
      mountPath: /maihar

  volumes:
  - name: maihar-volume
    emptyDir: {}