apiVersion: apps/v1
kind: Deployment

metadata:
  name: hr-web
  namespace: hr

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hr-web

  template:
    metadata:
      labels:
        app: hr-web

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80